# Generated by Django 3.2.24 on 2026-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_material_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
