# Generated by Django 3.2.24 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20260505_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLevelBOMEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_product_code', models.CharField(db_index=True, max_length=64)),
                ('parent_code', models.CharField(db_index=True, max_length=64)),
                ('parent_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SEMI', 'Semi-finished'), ('MATERIAL', 'Material')], max_length=16)),
                ('child_code', models.CharField(db_index=True, max_length=64)),
                ('child_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SEMI', 'Semi-finished'), ('MATERIAL', 'Material')], max_length=16)),
                ('quantity_per_parent', models.FloatField()),
                ('level', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['root_product_code', 'level', 'parent_code', 'child_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='multilevelbomedge',
            constraint=models.UniqueConstraint(fields=('root_product_code', 'parent_code', 'child_code'), name='uniq_multilevel_bom_edge'),
        ),
    ]
