# Generated by Django 6.0.5 on 2026-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salesdata_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('operations', 'Operations'), ('planning', 'Planning')], db_index=True, default='operations', max_length=20),
        ),
    ]
