# Generated by Django 6.0.5 on 2026-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transaction_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('quantity', models.FloatField()),
                ('source', models.CharField(choices=[('planning', 'Planning')], db_index=True, default='planning', max_length=20)),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('month', 'source')},
            },
        ),
    ]
