# Generated by Django 6.0.5 on 2026-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_monthlyproductiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_inventory', models.FloatField(default=0)),
                ('workers', models.IntegerField(default=50)),
                ('productivity', models.FloatField(default=150)),
                ('regular_cost', models.FloatField(default=0)),
                ('overtime_cost', models.FloatField(default=0)),
                ('subcontract_cost', models.FloatField(default=0)),
                ('inventory_cost', models.FloatField(default=0)),
                ('backorder_cost', models.FloatField(default=0)),
                ('ot_limit_pct', models.FloatField(default=20)),
                ('inventory_policy', models.FloatField(default=0)),
                ('current_workers', models.IntegerField(default=50)),
                ('hire_cost', models.FloatField(default=0)),
                ('layoff_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Planning Configurations',
            },
        ),
    ]
