# Generated by Django 6.0.5 on 2026-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_planningconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('month', models.DateField(db_index=True)),
                ('ratio', models.FloatField(default=0)),
                ('forecast_qty', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['month', 'product_code'],
                'unique_together': {('product_code', 'month')},
            },
        ),
    ]
