# Generated by Django 6.0.5 on 2026-05-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_customerorder_mpsconfiguration_disaggregatedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProductForMPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'ordering': ['-selected_at'],
                'unique_together': {('product',)},
            },
        ),
    ]
