# Generated by Django 6.0.5 on 2026-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_selectedproductformps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SEMI', 'Semi-finished'), ('MATERIAL', 'Material')], max_length=16)),
                ('lead_time', models.IntegerField(default=0)),
                ('on_hand', models.FloatField(default=0)),
                ('scheduled_receipts', models.JSONField(blank=True, default=list)),
                ('lot_policy', models.CharField(choices=[('L4L', 'Lot-for-Lot'), ('FOQ', 'Fixed Order Quantity'), ('PPA', 'PPA'), ('EOQ', 'EOQ')], default='L4L', max_length=8)),
                ('lot_size', models.FloatField(default=0)),
                ('safety_stock', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
    ]
